FROM python:latest

RUN mkdir /script

COPY model/text.py /script/.
COPY model/cos.py /script/.

RUN /usr/local/bin/python -m pip install requests
RUN /usr/local/bin/python -m pip install ibm-cos-sdk

CMD ["/usr/local/bin/python","/script/text.py","-a","472","-w","1","-c", "1"]
